project_id = "eqqggvtodrgbboebvglh"

[functions.create-payment]
verify_jwt = false

[functions.maps-api]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.send-marketing-emails]
verify_jwt = false

[functions.schedule-marketing-emails]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true