import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Navigation & Common
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.terms': 'Terms & Conditions',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.download': 'Download',
    
    // Welcome Screen
    'welcome.title': 'Professional Moving Services in Montreal',
    'welcome.subtitle': 'Reliable, efficient, and affordable moving solutions for your home or business.',
    'welcome.tagline': 'Your move, simplified. Get an instant quote and book your move in minutes.',
    'welcome.getQuote': 'Get Your Free Quote',
    'welcome.startMove': 'Start Your Move',
    'welcome.features.experience': '5+ Years Experience',
    'welcome.features.insured': 'Fully Insured',
    'welcome.features.support': '24/7 Support',
    'welcome.features.instantQuotes': 'Instant Quotes',
    'welcome.features.instantQuotesDesc': 'Get accurate pricing based on your specific items and distance',
    'welcome.features.professionalService': 'Professional Service',
    'welcome.features.professionalServiceDesc': 'Expert movers with 7 years of experience in the industry',
    'welcome.features.easyBooking': 'Easy Booking',
    'welcome.features.easyBookingDesc': 'Simple step-by-step process to schedule your move',
    'welcome.trust.rating': '4.9/5 Rating',
    'welcome.trust.customers': '1000+ Happy Customers',
    'welcome.trust.insured': 'Fully Insured',
    'welcome.copyright': '© 2021 Next Movement. All rights reserved.',
    
    // Step Indicator
    'steps.address': 'Addresses',
    'steps.service': 'Service Tier', 
    'steps.items': 'Items',
    'steps.quote': 'Quote',
    'steps.datetime': 'Date & Time',
    'steps.payment': 'Payment',
    'steps.confirmation': 'Confirmation',
    
    // Date Time Screen
    'datetime.title': 'When would you like to move?',
    'datetime.subtitle': 'Select your preferred date and time slot',
    'datetime.selectDate': 'Select Date',
    'datetime.selectTime': 'Select Time',
    'datetime.selectedDate': 'Selected Date',
    'datetime.selectedTime': 'Selected Time',
    'datetime.morning': 'Morning',
    'datetime.morningTime': '8:00 AM - 12:00 PM',
    'datetime.afternoon': 'Afternoon', 
    'datetime.afternoonTime': '12:00 PM - 5:00 PM',
    'datetime.evening': 'Evening',
    'datetime.eveningTime': '5:00 PM - 8:00 PM',
    
    // Service Tier Screen
    'servicetier.title': 'Choose Your Service Level',
    'servicetier.basic': 'Basic',
    'servicetier.premium': 'Premium',
    'servicetier.whiteglove': 'White Glove',
    'servicetier.popular': 'Popular',
    'servicetier.selectedService': 'Selected Service',
    'servicetier.basic.description': 'Standard move. Furniture protected with moving blankets. Packing boxes not included.',
    'servicetier.premium.description': 'Includes furniture disassembly/assembly, plus standard furniture protection.',
    'servicetier.whiteglove.description': 'Full-service move including disassembly/reassembly of furniture, and packing services with eco-friendly reusable bins for your small items.',
    'servicetier.features.professional': 'Professional moving team',
    'servicetier.features.protection': 'Furniture protection with blankets',
    'servicetier.features.liability': 'Standard liability coverage',
    'servicetier.features.loading': 'Loading & unloading',
    'servicetier.features.everything': 'Everything in Basic',
    'servicetier.features.enhanced': 'Enhanced liability coverage',
    'servicetier.features.disassembly': 'Furniture disassembly/assembly',
    'servicetier.features.everythingPremium': 'Everything in Premium',
    'servicetier.features.packing': 'Full packing & unpacking',
    'servicetier.features.setup': 'Setup & arrangement service',
    'servicetier.features.bins': '20 moving bins provided that are retrieved at the end of the move',
    
    // Payment Screen
    'payment.title': 'Payment Details',
    'payment.subtitle': 'Complete your booking with secure payment',
    'payment.personalInfo': 'Personal Information',
    'payment.fullName': 'Full Name',
    'payment.email': 'Email Address',
    'payment.phone': 'Phone Number',
    'payment.billingInfo': 'Billing Information',
    'payment.sameAsPickup': 'Same as pickup address',
    'payment.address': 'Address',
    'payment.city': 'City',
    'payment.postalCode': 'Postal Code',
    'payment.orderSummary': 'Order Summary',
    'payment.processing': 'Processing...',
    'payment.completeBooking': 'Complete Booking',
    'payment.termsText': 'By completing this booking, you agree to our',
    'payment.termsLink': 'Terms and Conditions',
    'payment.paymentInfo': 'Payment Information',
    
    // Common translations
    'back': 'Back',
    'continue': 'Continue',
    'estimatedDistance': 'Estimated distance',
    'calculatingRoute': 'Calculating route',
    
    // Address Screen
    'address.title': 'Where are you moving?',
    'address.subtitle': 'Add your pickup and drop-off locations',
    'address.pickup': 'Pickup Location',
    'address.dropoff': 'Drop-off Location',
    'address.addPickup': 'Add Pickup Location',
    'address.addDropoff': 'Add Drop-off Location',
    'address.placeholder': 'Enter address...',
    
    
    // Items Screen
    'items.title': 'What are you moving?',
    'items.subtitle': 'Select the items you need to move',
    'items.categories.bedroom': 'Bedroom',
    'items.categories.livingRoom': 'Living Room',
    'items.categories.kitchen': 'Kitchen',
    'items.categories.office': 'Office',
    'items.categories.appliances': 'Appliances',
    'items.categories.miscellaneous': 'Miscellaneous',
    'items.categories.outdoor': 'Outdoor',
    'items.categories.custom': 'Custom',
    'items.addCustom': 'Add Custom Item',
    'items.customName': 'Item Name',
    'items.customWeight': 'Weight (kg)',
    'items.customVolume': 'Volume (m³)',
    'items.quantity': 'Quantity',
    'items.currentSelection': 'Current Selection',
    'items.item': 'Item',
    'items.items': 'Items',
    'items.getQuote': 'Get Quote',
    'items.instructions': 'If you are unsure about one of your large items, pick the item that resembles it the most. If you have a small miscellaneous item that is not on the list, choose 1 packed box per item.',
    
    // Item Names
    'items.names.queenBedFrame': 'Bed Frame',
    'items.names.queenMattress': 'Mattress',
    'items.names.nightstand': 'Nightstand',
    'items.names.dresser6Drawer': 'Dresser',
    'items.names.chestOfDrawers': 'Chest of Drawers',
    'items.names.mirrorLarge': 'Mirror',
    'items.names.wardrobe': 'Wardrobe',
    'items.names.crib': 'Crib',
    'items.names.sofa3Seater': 'Sofa (3-seater)',
    'items.names.loveseat': 'Loveseat (2-seater)',
    'items.names.recliner': 'Recliner',
    'items.names.coffeeTable': 'Coffee Table',
    'items.names.endTable': 'End Table',
    'items.names.tvStandConsole': 'TV Stand/Console',
    'items.names.entertainmentCenter': 'Entertainment Center',
    'items.names.flatScreenTv55': 'Flat Screen TV',
    'items.names.cabinet': 'Cabinet',
    'items.names.buffetSideboard': 'Buffet/Sideboard',
    'items.names.diningTable6Person': 'Dining Table',
    'items.names.diningChair': 'Dining Chair',
    'items.names.refrigeratorFullSize': 'Refrigerator',
    'items.names.microwave': 'Microwave',
    'items.names.kitchenCartIsland': 'Kitchen Cart/Island',
    'items.names.officeDeskStandard': 'Office Desk',
    'items.names.officeChair': 'Office Chair',
    'items.names.filingCabinet2Drawer': 'Filing Cabinet (2-drawer)',
    'items.names.bookcaseLarge': 'Bookcase (Large)',
    'items.names.bookshelfMedium': 'Bookshelf (Medium)',
    'items.names.printerScanner': 'Printer/Scanner',
    'items.names.washer': 'Washer',
    'items.names.dryer': 'Dryer',
    'items.names.shoeRack': 'Shoe Rack',
    'items.names.laundryBasket': 'Laundry Basket',
    'items.names.storageBinPlastic': 'Storage Bin (Plastic)',
    'items.names.foldingChair': 'Folding Chair',
    'items.names.bicycle': 'Bicycle',
    'items.names.vacuumCleaner': 'Vacuum Cleaner',
    'items.names.floorLamp': 'Floor Lamp',
    'items.names.packedBox': 'Packed Box',
    
    // Quote Screen
    'quote.calculating': 'Calculating Your Quote',
    'quote.calculatingDesc': 'Please wait while we prepare your instant quote',
    'quote.analyzingItems': 'Analyzing your items...',
    'quote.analyzingDesc': 'This will only take a moment',
    'quote.title': 'Your Instant Quote',
    'quote.subtitle': 'Here\'s your personalized moving quote',
    'quote.breakdown': 'Quote Breakdown',
    'quote.baseService': 'Base Service Fee',
    'quote.itemCost': 'Items Cost',
    'quote.distanceFee': 'Distance Fee',
    'quote.subtotal': 'Subtotal',
    'quote.gst': 'GST (5%)',
    'quote.qst': 'QST (9.975%)',
    'quote.total': 'Total',
    'quote.selectedService': 'Selected Service',
    'quote.itemsSummary': 'Items Summary',
    'quote.items': 'Items',
    'quote.distance': 'Distance',
    'quote.whatsIncluded': 'What\'s Included in Your Quote',
    'quote.included1': 'Professional moving team',
    'quote.included2': 'All necessary equipment',
    'quote.included3': 'Loading and unloading',
    'quote.included4': 'Transportation between locations',
    'quote.included5': 'Basic insurance coverage',
    'quote.included6': 'No hidden fees',
    'quote.bookThisMove': 'Book This Move',
    'quote.emailQuote': 'Email me my quote',
    'quote.emailQuoteDesc': 'Get your quote sent to your email',
    'quote.emailSent': 'Quote sent to your email!',
    'quote.emailError': 'Failed to send email. Please try again.',
    'quote.enterEmail': 'Enter your email address',
    'quote.emailPlaceholder': 'your@email.com',
    'quote.send': 'Send Quote',
    'quote.cancel': 'Cancel',
    
    
    // Confirmation Screen
    'confirmation.title': 'Booking Confirmed!',
    'confirmation.subtitle': 'Your move has been successfully scheduled. A booking confirmation and receipt will be sent to you by email.',
    'confirmation.bookingId': 'Booking ID',
    'confirmation.dateTime': 'Date & Time',
    'confirmation.serviceDetails': 'Service Details',
    'confirmation.serviceTier': 'Service Tier',
    'confirmation.totalCost': 'Total Cost',
    'confirmation.locations': 'Locations',
    'confirmation.pickupLocation': 'Pickup Location(s)',
    'confirmation.dropoffLocation': 'Drop-off Location(s)',
    'confirmation.itemsSummary': 'Items Summary',
    'confirmation.totalItems': 'Total Items',
    'confirmation.contactInfo': 'Contact Information',
    'confirmation.needChanges': 'Need to make changes? Contact us at',
    'confirmation.downloadPdf': 'Download Move Details & Checklist',
    'confirmation.generating': 'Generating PDF...',
    'confirmation.bookAnother': 'Book Another Move',
    'confirmation.copyright': '© 2021 Next Movement. All rights reserved.',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'What areas do you serve?',
    'faq.a1': 'We provide moving services throughout Montreal and the greater Montreal area, including Laval, Longueuil, and surrounding suburbs.',
    'faq.q2': 'How far in advance should I book?',
    'faq.a2': 'We recommend booking at least 2 weeks in advance, especially during peak moving seasons (summer months and end/beginning of months).',
    'faq.q3': 'What is included in the moving service?',
    'faq.a3': 'Our standard service includes professional movers, moving truck, basic equipment (dollies, straps, blankets), and loading/unloading. Packing services are available as add-ons.',
    'faq.q4': 'Are my belongings insured?',
    'faq.a4': 'Yes, we provide basic coverage for your belongings. Additional insurance options are available for high-value items.',
    'faq.q5': 'What happens if there are delays?',
    'faq.a5': 'We strive to be punctual, but if delays occur due to unforeseen circumstances, we will notify you immediately and work to minimize any inconvenience.',
    'faq.q6': 'Do you provide packing materials?',
    'faq.a6': 'Yes, we offer a full range of packing materials including boxes, tape, bubble wrap, and packing paper. These can be purchased separately or as part of our packing service.',
    'faq.q7': 'Can you move pianos and special items?',
    'faq.a7': 'Yes, we have experience moving pianos, artwork, antiques, and other specialty items. Additional fees may apply for special handling.',
    'faq.q8': 'What payment methods do you accept?',
    'faq.a8': 'We accept cash, credit cards (Visa, Mastercard), and e-transfer. Payment is typically due upon completion of the move.',
    
    // Admin
    'admin.login': 'Admin Login',
    'admin.dashboard': 'Dashboard',
    'admin.bookings': 'Bookings',
    'admin.drivers': 'Drivers',
    'admin.analytics': 'Analytics',
    'admin.support': 'Support',
    'admin.settings': 'Settings',
    'admin.totalBookings': 'Total Bookings',
    'admin.todaysBookings': "Today's Bookings",
    'admin.activeDrivers': 'Active Drivers',
    'admin.totalRevenue': 'Total Revenue',
    'admin.pendingTickets': 'Pending Tickets',
    'admin.manageBookings': 'Manage Bookings',
    'admin.manageBookingsDesc': 'View, assign, and track all moving jobs',
    'admin.driverManagement': 'Driver Management',
    'admin.driverManagementDesc': 'Manage drivers, schedules, and assignments',
    'admin.customerSupport': 'Customer Support',
    'admin.customerSupportDesc': 'Handle customer inquiries and issues',
    'admin.companyAvailability': 'Company Availability',
    'admin.companyAvailabilityDesc': 'Manage operating hours and blackout dates',
    'admin.analyticsDesc': 'View reports and business insights',
    'admin.settingsDesc': 'Manage users, pricing, and system settings',
    'admin.customerPortal': 'Customer Portal',
    'admin.customerPortalDesc': 'Go to the customer booking interface',
    'admin.adminPortal': 'NextMovement Admin',
    'admin.welcomeBack': 'Welcome back',
    'admin.logout': 'Logout',
    'admin.backToDashboard': 'Back to Dashboard',
    'admin.bookingManagement': 'Booking Management',
    'admin.createUser': 'Create New User',
    'admin.createUserDesc': 'Add new admin or driver users to the system',
    'admin.role': 'Role',
    'admin.admin': 'Admin',
    'admin.driver': 'Driver',
    'admin.pricingSettings': 'Pricing Settings',
    'admin.pricingSettingsDesc': 'Configure base rates, service tier multipliers, and tax rates',
    'admin.userManagement': 'User Management',
    'admin.userManagementDesc': 'Manage existing users, roles, and permissions',
    
    // Support Tickets
    'support.createTicket': 'Submit Support Request',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.priority': 'Priority',
    'support.low': 'Low',
    'support.medium': 'Medium',
    'support.high': 'High',
    'support.submitTicket': 'Submit Ticket',
    'support.ticketSubmitted': 'Support ticket submitted successfully',
    'support.ticketError': 'Error submitting support ticket',
    
    // Error Messages
    'error.addressRequired': 'Please add at least one pickup and one drop-off address',
    'error.dateRequired': 'Please select a date and time',
    'error.serviceRequired': 'Please select a service tier',
    'error.itemsRequired': 'Please select at least one item',
    'error.paymentRequired': 'Please fill in all required payment information',
    
    // Success Messages
    'success.bookingSaved': 'Booking saved successfully',
    'success.emailSent': 'Confirmation email sent',
    'success.pdfGenerated': 'PDF generated successfully',
    
    // Help & Support translations
    helpSupport: 'Help & Support',
    customerSupport: 'Customer Support',
    viewFAQ: 'View FAQ',
    phone: 'Phone',
    email: 'Email',
    customerServiceDescription: 'Our customer service team is here to help with any questions or concerns about your move.',
    
    // FAQ translations
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    backToHome: 'Back to Home',
    faqNeedMoreHelp: 'Need more help? Contact us directly at',
    or: 'or',
    readyToGetStarted: 'Ready to get started?',
    getYourFreeQuote: 'Get Your Free Quote',
    
    // FAQ Sections
    faqServiceAreasTitle: 'Service Areas & Coverage',
    faqServiceAreasQ1: 'What areas do you service?',
    faqServiceAreasA1: 'We primarily serve the Greater Montreal Area and surrounding regions, including Laval, Longueuil, and the South Shore. For long-distance moves, please contact us directly.',
    faqServiceAreasQ2: 'Do you offer long-distance moves?',
    faqServiceAreasA2: 'Yes, we provide both local and long-distance moving services across Quebec and neighboring provinces. Quotes may vary based on mileage and complexity.',
    
    faqServicesTitle: 'Services & Equipment',
    faqServicesQ1: 'Can you move pianos or heavy furniture?',
    faqServicesA1: 'We move heavy furniture but unfortunately, we do not move pianos.',
    faqServicesQ2: 'Do you provide packing materials?',
    faqServicesA2: 'Yes, for White Glove service tier, we offer boxes, tape, bubble wrap, and other packing supplies.',
    faqServicesQ3: 'Can I hire movers without a truck?',
    faqServicesA3: 'Yes, we offer labor-only services for loading/unloading or in-home moves where transportation isn\'t required. For a move with a truck you supply, the base service fee and distance fee would be waived. For commercial labor such as offices and warehouses, contact the customer service number at (438) 543-0904.',
    faqServicesQ4: 'Do you disassemble and reassemble furniture?',
    faqServicesA4: 'Yes, our team can disassemble and reassemble beds, tables, and other furniture as part of the move with the Premium service tier.',
    faqServicesQ5: 'What\'s included in each service tier?',
    faqServicesA5: 'Our service tiers vary from basic loading/unloading to full-service moves with packing, materials, and furniture assembly. You\'ll see details during booking.',
    
    faqPricingTitle: 'Pricing & Costs',
    faqPricingQ1: 'How much does a 1-bedroom apartment move cost?',
    faqPricingA1: 'Prices typically start at $350–$600 for a 1-bedroom move, depending on the distance, items, and service tier. Use our online quote tool for an instant estimate.',
    faqPricingQ2: 'Is your quote final or will there be extra charges?',
    faqPricingA2: 'The quote you receive is a final flat rate based on the inventory and details you provide. Additional charges only apply for last-minute changes or significant item additions.',
    faqPricingQ3: 'Do you charge hourly or flat rate?',
    faqPricingA3: 'We use flat-rate pricing for transparency and simplicity. However, hourly rates may apply in custom or special cases (commercial jobs).',
    
    faqBookingTitle: 'Booking & Scheduling',
    faqBookingQ1: 'How far in advance should I book?',
    faqBookingA1: 'We recommend booking 2–3 weeks in advance, especially during weekends or at the end of the month when demand is highest.',
    faqBookingQ2: 'Can I change my moving date after booking?',
    faqBookingA2: 'Yes, you can reschedule up to 48 hours before your move without penalty, contact support to make changes.',
    faqBookingQ3: 'Do you offer same-day or next-day service?',
    faqBookingA3: 'We do offer last-minute bookings when availability allows. Contact us or check online for real-time scheduling.',
    faqBookingQ4: 'What time will the movers arrive?',
    faqBookingA4: 'You\'ll be given a time window when booking, and our team will confirm 24 hours before your move. We also send live updates the day of.',
    faqBookingQ5: 'Can I schedule a move for the evening or weekend?',
    faqBookingA5: 'Yes, we operate 7 days a week and offer evening time slots to accommodate your schedule.',
    
    // Terms & Conditions
    termsConditions: 'Terms and Conditions',
    questions: 'Questions?',
    termsQuestionsDesc: 'If you have any questions about these terms and conditions, please don\'t hesitate to contact us:',
    
    refundDisputePolicy: 'Refund and Dispute Policy',
    refundEligibility: 'Refund Eligibility',
    refundEligibilityDesc: 'Refunds may be considered under the following circumstances:',
    refundEligibility1: 'Service cancellation with proper notice (48+ hours in advance)',
    refundEligibility2: 'Failure to provide agreed-upon services',
    refundEligibility3: 'Damage to property due to negligence on our part',
    disputeResolution: 'Dispute Resolution',
    disputeResolutionDesc: 'Any disputes regarding services or charges should be reported within 48 hours of the moving date. We are committed to resolving all disputes fairly and promptly through direct communication with our customer service team.',
    refundProcess: 'Refund Process',
    refundProcessDesc: 'Approved refunds will be processed within 5-10 business days and credited back to the original payment method.',
    
    cancellationPolicy: 'Cancellation Policy',
    noticeRequirement: '48-Hour Notice Requirement',
    noticeRequirementDesc: 'Cancellations made less than 48 hours in advance of the reserved moving time slot are non-refundable.',
    noticeRequirementReason: 'This policy is in place due to the specialized nature of our services and the advance scheduling required for our moving teams and equipment.',
    howToCancel: 'How to Cancel',
    howToCancelDesc: 'To cancel your moving service, please contact our customer service team:',
    weatherEmergencyTitle: 'Weather and Emergency Cancellations',
    weatherEmergencyDesc: 'In cases of severe weather or emergency situations that make moving unsafe, we may need to reschedule your move. In such cases, no cancellation fees apply, and we will work with you to find an alternative date.',
    
    additionalCharges: 'Additional Charges',
    undeclaredItems: 'Undeclared Items',
    undeclaredItemsDesc: 'On moving day, any undeclared items are subject to additional charges.',
    undeclaredItemsDetail: 'All items to be moved must be declared during the booking process to ensure accurate pricing and proper preparation. Additional items discovered on moving day will be charged at current market rates.',
    undeclaredAddresses: 'Undeclared Addresses',
    undeclaredAddressesDesc: 'Any undeclared addresses on moving day are subject to additional charges.',
    undeclaredAddressesDetail: 'All pickup and drop-off locations must be specified during booking. Additional stops or address changes on the day of the move will incur extra charges based on distance and time required.',
    otherAdditionalCharges: 'Other Additional Charges',
    otherAdditionalChargesDesc: 'Additional charges may apply for:',
    additionalCharge1: 'Packing services requested on moving day',
    additionalCharge2: 'Waiting time due to customer delays',
    
    // Chatbot
    chatbotWelcome: 'Hello! I\'m here to help with any questions about our moving services. How can I assist you today?',
    chatbotTitle: 'Next Movement Support',
    chatbotPlaceholder: 'Type your message...',
    chatbotError: 'Sorry, I\'m having trouble responding right now. Please try again or contact customer service.',
    error: 'Error',
  },
  fr: {
    // Navigation & Common
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.terms': 'Termes et Conditions',
    'common.next': 'Suivant',
    'common.back': 'Retour',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.close': 'Fermer',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.download': 'Télécharger',
    
    // Welcome Screen
    'welcome.title': 'Services de Déménagement Professionnels à Montréal',
    'welcome.subtitle': 'Solutions de déménagement fiables, efficaces et abordables pour votre maison ou entreprise.',
    'welcome.tagline': 'Votre déménagement, simplifié. Obtenez un devis instantané et réservez votre déménagement en quelques minutes.',
    'welcome.getQuote': 'Obtenez Votre Devis Gratuit',
    'welcome.startMove': 'Commencez Votre Déménagement',
    'welcome.features.experience': '5+ Années d\'Expérience',
    'welcome.features.insured': 'Entièrement Assuré',
    'welcome.features.support': 'Support 24/7',
    'welcome.features.instantQuotes': 'Devis Instantanés',
    'welcome.features.instantQuotesDesc': 'Obtenez une tarification précise basée sur vos articles spécifiques et la distance',
    'welcome.features.professionalService': 'Service Professionnel',
    'welcome.features.professionalServiceDesc': 'Déménageurs experts avec 7 années d\'expérience dans l\'industrie',
    'welcome.features.easyBooking': 'Réservation Facile',
    'welcome.features.easyBookingDesc': 'Processus simple étape par étape pour programmer votre déménagement',
    'welcome.trust.rating': 'Note 4.9/5',
    'welcome.trust.customers': '1000+ Clients Satisfaits',
    'welcome.trust.insured': 'Entièrement Assuré',
    'welcome.copyright': '© 2021 Next Movement. Tous droits réservés.',
    
    // Step Indicator
    'steps.address': 'Adresse',
    'steps.service': 'Service',
    'steps.items': 'Articles', 
    'steps.quote': 'Devis',
    'steps.datetime': 'Date',
    'steps.payment': 'Paiement',
    'steps.confirmation': 'Confirmation',
    
    // Date Time Screen
    'datetime.title': 'Quand souhaitez-vous déménager?',
    'datetime.subtitle': 'Sélectionnez votre date et créneau horaire préférés',
    'datetime.selectDate': 'Sélectionner une Date',
    'datetime.selectTime': 'Sélectionner l\'Heure',
    'datetime.selectedDate': 'Date Sélectionnée',
    'datetime.selectedTime': 'Heure Sélectionnée',
    'datetime.morning': 'Matin',
    'datetime.morningTime': '8h00 - 12h00',
    'datetime.afternoon': 'Après-midi',
    'datetime.afternoonTime': '12h00 - 17h00', 
    'datetime.evening': 'Soir',
    'datetime.eveningTime': '17h00 - 20h00',
    
    // Service Tier Screen
    'servicetier.title': 'Choisissez Votre Niveau de Service',
    'servicetier.basic': 'De Base',
    'servicetier.premium': 'Premium',
    'servicetier.whiteglove': 'Service Complet',
    'servicetier.popular': 'Populaire',
    'servicetier.selectedService': 'Service Sélectionné',
    'servicetier.basic.description': 'Déménagement standard. Meubles protégés avec des couvertures de déménagement. Boîtes d\'emballage non incluses.',
    'servicetier.premium.description': 'Inclut le démontage/remontage de meubles, plus la protection standard des meubles.',
    'servicetier.whiteglove.description': 'Déménagement complet incluant le démontage/remontage de meubles et services d\'emballage avec bacs réutilisables écologiques pour vos petits objets.',
    'servicetier.features.professional': 'Équipe de déménagement professionnelle',
    'servicetier.features.protection': 'Protection des meubles avec couvertures',
    'servicetier.features.liability': 'Couverture de responsabilité standard',
    'servicetier.features.loading': 'Chargement et déchargement',
    'servicetier.features.everything': 'Tout ce qui est dans De Base',
    'servicetier.features.enhanced': 'Couverture de responsabilité améliorée',
    'servicetier.features.disassembly': 'Démontage/remontage de meubles',
    'servicetier.features.everythingPremium': 'Tout ce qui est dans Premium',
    'servicetier.features.packing': 'Emballage et déballage complets',
    'servicetier.features.setup': 'Service d\'installation et d\'aménagement',
    'servicetier.features.bins': '20 bacs de déménagement fournis qui sont récupérés à la fin du déménagement',
    
    // Payment Screen
    'payment.title': 'Information de Paiement',
    'payment.subtitle': 'Complétez votre réservation avec un paiement sécurisé',
    'payment.personalInfo': 'Informations Personnelles',
    'payment.fullName': 'Nom Complet',
    'payment.email': 'Adresse E-mail',
    'payment.phone': 'Numéro de Téléphone',
    'payment.billingInfo': 'Informations de Facturation',
    'payment.sameAsPickup': 'Identique à l\'adresse de collecte',
    'payment.address': 'Adresse',
    'payment.city': 'Ville',
    'payment.postalCode': 'Code Postal',
    'payment.orderSummary': 'Résumé de Commande',
    'payment.processing': 'Traitement en cours...',
    'payment.completeBooking': 'Finaliser la Réservation',
    'payment.termsText': 'En finalisant cette réservation, vous acceptez nos',
    'payment.termsLink': 'Conditions Générales',
    'payment.paymentInfo': 'Information de Paiement',
    
    // Common translations
    'back': 'Retour',
    'continue': 'Continuer',
    'estimatedDistance': 'Distance estimée',
    'calculatingRoute': 'Calcul de l\'itinéraire',
    
    // Address Screen
    'address.title': 'Où déménagez-vous?',
    'address.subtitle': 'Ajoutez vos lieux de ramassage et de livraison',
    'address.pickup': 'Lieu de Ramassage',
    'address.dropoff': 'Lieu de Livraison',
    'address.addPickup': 'Ajouter un Lieu de Ramassage',
    'address.addDropoff': 'Ajouter un Lieu de Livraison',
    'address.placeholder': 'Entrez l\'adresse...',
    
    
    // Items Screen
    'items.title': 'Que déménagez-vous?',
    'items.subtitle': 'Sélectionnez les articles que vous devez déménager',
    'items.categories.bedroom': 'Chambre',
    'items.categories.livingRoom': 'Salon',
    'items.categories.kitchen': 'Cuisine',
    'items.categories.office': 'Bureau',
    'items.categories.appliances': 'Électroménagers',
    'items.categories.miscellaneous': 'Divers',
    'items.categories.outdoor': 'Extérieur',
    'items.categories.custom': 'Personnalisé',
    'items.addCustom': 'Ajouter un Article Personnalisé',
    'items.customName': 'Nom de l\'Article',
    'items.customWeight': 'Poids (kg)',
    'items.customVolume': 'Volume (m³)',
    'items.quantity': 'Quantité',
    'items.currentSelection': 'Sélection Actuelle',
    'items.item': 'Article',
    'items.items': 'Articles',
    'items.getQuote': 'Obtenir un Devis',
    'items.instructions': 'Si vous n\'êtes pas sûr d\'un de vos gros articles, choisissez l\'article qui lui ressemble le plus. Si vous avez un petit article divers qui n\'est pas sur la liste, choisissez 1 boîte emballée par article.',
    
    // Item Names
    'items.names.queenBedFrame': 'Cadre de Lit Queen',
    'items.names.queenMattress': 'Matelas Queen',
    'items.names.nightstand': 'Table de Chevet',
    'items.names.dresser6Drawer': 'Commode 6 Tiroirs',
    'items.names.chestOfDrawers': 'Commode à Tiroirs',
    'items.names.mirrorLarge': 'Grand Miroir',
    'items.names.wardrobe': 'Garde-robe',
    'items.names.crib': 'Berceau',
    'items.names.sofa3Seater': 'Canapé (3 places)',
    'items.names.loveseat': 'Causeuse (2 places)',
    'items.names.recliner': 'Fauteuil Inclinable',
    'items.names.coffeeTable': 'Table Basse',
    'items.names.endTable': 'Table d\'Appoint',
    'items.names.tvStandConsole': 'Meuble TV/Console',
    'items.names.entertainmentCenter': 'Centre de Divertissement',
    'items.names.flatScreenTv55': 'Télé à Écran Plat 55"',
    'items.names.cabinet': 'Armoire',
    'items.names.buffetSideboard': 'Buffet/Bahut',
    'items.names.diningTable6Person': 'Table à Manger 6 Personnes',
    'items.names.diningChair': 'Chaise de Salle à Manger',
    'items.names.refrigeratorFullSize': 'Réfrigérateur Grande Taille',
    'items.names.microwave': 'Micro-ondes',
    'items.names.kitchenCartIsland': 'Chariot/Îlot de Cuisine',
    'items.names.officeDeskStandard': 'Bureau de Travail Standard',
    'items.names.officeChair': 'Chaise de Bureau',
    'items.names.filingCabinet2Drawer': 'Classeur (2 tiroirs)',
    'items.names.bookcaseLarge': 'Bibliothèque (Grande)',
    'items.names.bookshelfMedium': 'Étagère (Moyenne)',
    'items.names.printerScanner': 'Imprimante/Scanner',
    'items.names.washer': 'Laveuse',
    'items.names.dryer': 'Sécheuse',
    'items.names.shoeRack': 'Porte-chaussures',
    'items.names.laundryBasket': 'Panier à Linge',
    'items.names.storageBinPlastic': 'Bac de Rangement (Plastique)',
    'items.names.foldingChair': 'Chaise Pliante',
    'items.names.bicycle': 'Vélo',
    'items.names.vacuumCleaner': 'Aspirateur',
    'items.names.floorLamp': 'Lampe sur Pied',
    'items.names.packedBox': 'Boîte Emballée',
    
    // Quote Screen
    'quote.calculating': 'Calcul de Votre Devis',
    'quote.calculatingDesc': 'Veuillez patienter pendant que nous préparons votre devis instantané',
    'quote.analyzingItems': 'Analyse de vos articles...',
    'quote.analyzingDesc': 'Cela ne prendra qu\'un instant',
    'quote.title': 'Votre Devis Instantané',
    'quote.subtitle': 'Voici votre devis de déménagement personnalisé',
    'quote.breakdown': 'Détail du Devis',
    'quote.baseService': 'Frais de Service de Base',
    'quote.itemCost': 'Coût des Articles',
    'quote.distanceFee': 'Frais de Distance',
    'quote.subtotal': 'Sous-total',
    'quote.gst': 'TPS (5%)',
    'quote.qst': 'TVQ (9.975%)',
    'quote.total': 'Total',
    'quote.selectedService': 'Service Sélectionné',
    'quote.itemsSummary': 'Résumé des Articles',
    'quote.items': 'Articles',
    'quote.distance': 'Distance',
    'quote.whatsIncluded': 'Ce qui est Inclus dans Votre Devis',
    'quote.included1': 'Équipe de déménagement professionnelle',
    'quote.included2': 'Tout l\'équipement nécessaire',
    'quote.included3': 'Chargement et déchargement',
    'quote.included4': 'Transport entre les emplacements',
    'quote.included5': 'Couverture d\'assurance de base',
    'quote.included6': 'Aucuns frais cachés',
    'quote.bookThisMove': 'Réserver ce Déménagement',
    'quote.emailQuote': 'Envoyez-moi mon devis',
    'quote.emailQuoteDesc': 'Recevez votre devis par email',
    'quote.emailSent': 'Devis envoyé à votre email!',
    'quote.emailError': 'Échec de l\'envoi de l\'email. Veuillez réessayer.',
    'quote.enterEmail': 'Entrez votre adresse email',
    'quote.emailPlaceholder': 'votre@email.com',
    'quote.send': 'Envoyer le devis',
    'quote.cancel': 'Annuler',
    
    
    // Confirmation Screen
    'confirmation.title': 'Réservation Confirmée!',
    'confirmation.subtitle': 'Votre déménagement a été programmé avec succès. Une confirmation de réservation et un reçu vous seront envoyés par e-mail.',
    'confirmation.bookingId': 'ID de Réservation',
    'confirmation.dateTime': 'Date et Heure',
    'confirmation.serviceDetails': 'Détails du Service',
    'confirmation.serviceTier': 'Niveau de Service',
    'confirmation.totalCost': 'Coût Total',
    'confirmation.locations': 'Emplacements',
    'confirmation.pickupLocation': 'Lieu(x) de Ramassage',
    'confirmation.dropoffLocation': 'Lieu(x) de Livraison',
    'confirmation.itemsSummary': 'Résumé des Articles',
    'confirmation.totalItems': 'Total des Articles',
    'confirmation.contactInfo': 'Informations de Contact',
    'confirmation.needChanges': 'Besoin de faire des changements? Contactez-nous au',
    'confirmation.downloadPdf': 'Télécharger les Détails et Liste de Vérification',
    'confirmation.generating': 'Génération du PDF...',
    'confirmation.bookAnother': 'Réserver un Autre Déménagement',
    'confirmation.copyright': '© 2021 Next Movement. Tous droits réservés.',
    
    // FAQ
    'faq.title': 'Questions Fréquemment Posées',
    'faq.q1': 'Quelles zones desservez-vous?',
    'faq.a1': 'Nous fournissons des services de déménagement dans tout Montréal et la grande région de Montréal, y compris Laval, Longueuil et les banlieues environnantes.',
    'faq.q2': 'Combien de temps à l\'avance dois-je réserver?',
    'faq.a2': 'Nous recommandons de réserver au moins 2 semaines à l\'avance, surtout pendant les saisons de pointe (mois d\'été et fin/début de mois).',
    'faq.q3': 'Qu\'est-ce qui est inclus dans le service de déménagement?',
    'faq.a3': 'Notre service standard comprend des déménageurs professionnels, un camion de déménagement, de l\'équipement de base (diables, sangles, couvertures), et le chargement/déchargement. Les services d\'emballage sont disponibles en option.',
    'faq.q4': 'Mes biens sont-ils assurés?',
    'faq.a4': 'Oui, nous fournissons une couverture de base pour vos biens. Des options d\'assurance supplémentaires sont disponibles pour les articles de grande valeur.',
    'faq.q5': 'Que se passe-t-il s\'il y a des retards?',
    'faq.a5': 'Nous nous efforçons d\'être ponctuels, mais si des retards surviennent en raison de circonstances imprévues, nous vous en informerons immédiatement et travaillerons pour minimiser tout inconvénient.',
    'faq.q6': 'Fournissez-vous du matériel d\'emballage?',
    'faq.a6': 'Oui, nous offrons une gamme complète de matériaux d\'emballage incluant des boîtes, du ruban adhésif, du papier bulle et du papier d\'emballage. Ceux-ci peuvent être achetés séparément ou dans le cadre de notre service d\'emballage.',
    'faq.q7': 'Pouvez-vous déménager des pianos et des articles spéciaux?',
    'faq.a7': 'Oui, nous avons de l\'expérience dans le déménagement de pianos, d\'œuvres d\'art, d\'antiquités et d\'autres articles spécialisés. Des frais supplémentaires peuvent s\'appliquer pour la manipulation spéciale.',
    'faq.q8': 'Quels modes de paiement acceptez-vous?',
    'faq.a8': 'Nous acceptons l\'argent comptant, les cartes de crédit (Visa, Mastercard) et les virements électroniques. Le paiement est généralement dû à la fin du déménagement.',
    
    // Admin
    'admin.login': 'Connexion Administrateur',
    'admin.dashboard': 'Tableau de Bord',
    'admin.bookings': 'Réservations',
    'admin.drivers': 'Chauffeurs',
    'admin.analytics': 'Analytiques',
    'admin.support': 'Support',
    'admin.settings': 'Paramètres',
    'admin.totalBookings': 'Total Réservations',
    'admin.todaysBookings': "Réservations d'Aujourd'hui",
    'admin.activeDrivers': 'Chauffeurs Actifs',
    'admin.totalRevenue': 'Revenus Totaux',
    'admin.pendingTickets': 'Tickets en Attente',
    'admin.manageBookings': 'Gérer les Réservations',
    'admin.manageBookingsDesc': 'Voir, assigner et suivre tous les travaux de déménagement',
    'admin.driverManagement': 'Gestion des Chauffeurs',
    'admin.driverManagementDesc': 'Gérer les chauffeurs, horaires et assignations',
    'admin.customerSupport': 'Support Client',
    'admin.customerSupportDesc': 'Gérer les demandes et problèmes des clients',
    'admin.companyAvailability': 'Disponibilité de la Compagnie',
    'admin.companyAvailabilityDesc': 'Gérer les heures d\'ouverture et dates d\'indisponibilité',
    'admin.analyticsDesc': 'Voir les rapports et insights d\'affaires',
    'admin.settingsDesc': 'Gérer les utilisateurs, tarification et paramètres système',
    'admin.customerPortal': 'Portail Client',
    'admin.customerPortalDesc': 'Aller à l\'interface de réservation client',
    'admin.adminPortal': 'Administration NextMovement',
    'admin.welcomeBack': 'Bon retour',
    'admin.logout': 'Déconnexion',
    'admin.backToDashboard': 'Retour au Tableau de Bord',
    'admin.bookingManagement': 'Gestion des Réservations',
    'admin.createUser': 'Créer Nouvel Utilisateur',
    'admin.createUserDesc': 'Ajouter de nouveaux administrateurs ou chauffeurs au système',
    'admin.role': 'Rôle',
    'admin.admin': 'Administrateur',
    'admin.driver': 'Chauffeur',
    'admin.pricingSettings': 'Paramètres de Tarification',
    'admin.pricingSettingsDesc': 'Configurer les tarifs de base, multiplicateurs de niveaux de service et taux de taxes',
    'admin.userManagement': 'Gestion des Utilisateurs',
    'admin.userManagementDesc': 'Gérer les utilisateurs existants, rôles et permissions',
    
    // Support Tickets
    'support.createTicket': 'Soumettre une Demande de Support',
    'support.subject': 'Sujet',
    'support.message': 'Message',
    'support.priority': 'Priorité',
    'support.low': 'Faible',
    'support.medium': 'Moyenne',
    'support.high': 'Élevée',
    'support.submitTicket': 'Soumettre le Ticket',
    'support.ticketSubmitted': 'Ticket de support soumis avec succès',
    'support.ticketError': 'Erreur lors de la soumission du ticket de support',
    
    // Error Messages
    'error.addressRequired': 'Veuillez ajouter au moins une adresse de ramassage et une de livraison',
    'error.dateRequired': 'Veuillez sélectionner une date et une heure',
    'error.serviceRequired': 'Veuillez sélectionner un niveau de service',
    'error.itemsRequired': 'Veuillez sélectionner au moins un article',
    'error.paymentRequired': 'Veuillez remplir toutes les informations de paiement requises',
    
    // Success Messages
    'success.bookingSaved': 'Réservation enregistrée avec succès',
    'success.emailSent': 'E-mail de confirmation envoyé',
    'success.pdfGenerated': 'PDF généré avec succès',
    
    // Help & Support translations
    helpSupport: 'Aide et Support',
    customerSupport: 'Support Client',
    viewFAQ: 'Voir FAQ',
    phone: 'Téléphone',
    email: 'Courriel',
    customerServiceDescription: 'Notre équipe de service clientèle est là pour vous aider avec toutes questions ou préoccupations concernant votre déménagement.',
    
    // FAQ translations
    frequentlyAskedQuestions: 'Questions Fréquemment Posées',
    backToHome: 'Retour à l\'Accueil',
    faqNeedMoreHelp: 'Besoin d\'aide supplémentaire ? Contactez-nous directement au',
    or: 'ou',
    readyToGetStarted: 'Prêt à commencer ?',
    getYourFreeQuote: 'Obtenez Votre Devis Gratuit',
    
    // FAQ Sections
    faqServiceAreasTitle: 'Zones de Service et Couverture',
    faqServiceAreasQ1: 'Quelles zones desservez-vous ?',
    faqServiceAreasA1: 'Nous desservons principalement la région du Grand Montréal et les régions environnantes, incluant Laval, Longueuil et la Rive-Sud. Pour les déménagements longue distance, veuillez nous contacter directement.',
    faqServiceAreasQ2: 'Offrez-vous des déménagements longue distance ?',
    faqServiceAreasA2: 'Oui, nous offrons des services de déménagement local et longue distance à travers le Québec et les provinces voisines. Les devis peuvent varier selon le kilométrage et la complexité.',
    
    faqServicesTitle: 'Services et Équipement',
    faqServicesQ1: 'Pouvez-vous déménager des pianos ou des meubles lourds ?',
    faqServicesA1: 'Nous déménageons des meubles lourds mais malheureusement, nous ne déménageons pas les pianos.',
    faqServicesQ2: 'Fournissez-vous du matériel d\'emballage ?',
    faqServicesA2: 'Oui, pour le niveau de service Service Complet, nous offrons des boîtes, ruban adhésif, papier bulle et autres fournitures d\'emballage.',
    faqServicesQ3: 'Puis-je engager des déménageurs sans camion ?',
    faqServicesA3: 'Oui, nous offrons des services de main-d\'œuvre seulement pour le chargement/déchargement ou les déménagements dans la maison où le transport n\'est pas requis.',
    faqServicesQ4: 'Démontez-vous et remontez-vous les meubles ?',
    faqServicesA4: 'Oui, notre équipe peut démonter et remonter les lits, tables et autres meubles dans le cadre du déménagement avec le niveau de service Premium.',
    faqServicesQ5: 'Qu\'est-ce qui est inclus dans chaque niveau de service ?',
    faqServicesA5: 'Nos niveaux de service varient du chargement/déchargement de base aux déménagements complets avec emballage, matériaux et assemblage de meubles.',
    
    faqPricingTitle: 'Tarification et Coûts',
    faqPricingQ1: 'Combien coûte le déménagement d\'un appartement 1 chambre ?',
    faqPricingA1: 'Les prix commencent généralement entre 350$ et 600$ pour un déménagement 1 chambre, selon la distance, les articles et le niveau de service.',
    faqPricingQ2: 'Votre devis est-il final ou y aura-t-il des frais supplémentaires ?',
    faqPricingA2: 'Le devis que vous recevez est un tarif forfaitaire final basé sur l\'inventaire et les détails que vous fournissez.',
    faqPricingQ3: 'Facturez-vous à l\'heure ou au forfait ?',
    faqPricingA3: 'Nous utilisons une tarification forfaitaire pour la transparence et la simplicité.',
    
    faqBookingTitle: 'Réservation et Planification',
    faqBookingQ1: 'À quelle avance dois-je réserver ?',
    faqBookingA1: 'Nous recommandons de réserver 2 à 3 semaines à l\'avance, surtout pendant les fins de semaine.',
    faqBookingQ2: 'Puis-je changer ma date de déménagement après la réservation ?',
    faqBookingA2: 'Oui, vous pouvez reprogrammer jusqu\'à 48 heures avant votre déménagement sans pénalité.',
    faqBookingQ3: 'Offrez-vous un service le jour même ou le lendemain ?',
    faqBookingA3: 'Nous offrons des réservations de dernière minute quand la disponibilité le permet.',
    faqBookingQ4: 'À quelle heure les déménageurs arriveront-ils ?',
    faqBookingA4: 'On vous donnera une fenêtre de temps lors de la réservation, et notre équipe confirmera 24 heures avant.',
    faqBookingQ5: 'Puis-je planifier un déménagement en soirée ou la fin de semaine ?',
    faqBookingA5: 'Oui, nous opérons 7 jours par semaine et offrons des créneaux horaires en soirée.',
    
    // Terms & Conditions
    termsConditions: 'Conditions d\'Utilisation',
    questions: 'Questions ?',
    termsQuestionsDesc: 'Si vous avez des questions concernant ces conditions d\'utilisation, n\'hésitez pas à nous contacter :',
    
    refundDisputePolicy: 'Politique de Remboursement et de Litige',
    refundEligibility: 'Admissibilité au Remboursement',
    refundEligibilityDesc: 'Les remboursements peuvent être considérés dans les circonstances suivantes :',
    refundEligibility1: 'Annulation de service avec préavis approprié (48+ heures à l\'avance)',
    refundEligibility2: 'Échec de fournir les services convenus',
    refundEligibility3: 'Dommages à la propriété dus à la négligence de notre part',
    disputeResolution: 'Résolution de Litiges',
    disputeResolutionDesc: 'Tout litige concernant les services ou frais doit être signalé dans les 48 heures suivant la date de déménagement.',
    refundProcess: 'Processus de Remboursement',
    refundProcessDesc: 'Les remboursements approuvés seront traités dans les 5 à 10 jours ouvrables.',
    
    cancellationPolicy: 'Politique d\'Annulation',
    noticeRequirement: 'Exigence de Préavis de 48 Heures',
    noticeRequirementDesc: 'Les annulations faites moins de 48 heures à l\'avance du créneau de déménagement réservé sont non remboursables.',
    noticeRequirementReason: 'Cette politique est en place en raison de la nature spécialisée de nos services.',
    howToCancel: 'Comment Annuler',
    howToCancelDesc: 'Pour annuler votre service de déménagement, veuillez contacter notre équipe de service clientèle :',
    weatherEmergencyTitle: 'Annulations Météo et d\'Urgence',
    weatherEmergencyDesc: 'En cas de conditions météorologiques sévères, nous pourrions devoir reprogrammer votre déménagement.',
    
    additionalCharges: 'Frais Supplémentaires',
    undeclaredItems: 'Articles Non Déclarés',
    undeclaredItemsDesc: 'Le jour du déménagement, tout article non déclaré est sujet à des frais supplémentaires.',
    undeclaredItemsDetail: 'Tous les articles à déménager doivent être déclarés pendant le processus de réservation.',
    undeclaredAddresses: 'Adresses Non Déclarées',
    undeclaredAddressesDesc: 'Toute adresse non déclarée le jour du déménagement est sujette à des frais supplémentaires.',
    undeclaredAddressesDetail: 'Tous les lieux de ramassage et de livraison doivent être spécifiés lors de la réservation.',
    otherAdditionalCharges: 'Autres Frais Supplémentaires',
    otherAdditionalChargesDesc: 'Des frais supplémentaires peuvent s\'appliquer pour :',
    additionalCharge1: 'Services d\'emballage demandés le jour du déménagement',
    additionalCharge2: 'Temps d\'attente dû aux retards du client',
    
    // Chatbot
    chatbotWelcome: 'Bonjour ! Je suis là pour vous aider avec toutes questions concernant nos services de déménagement. Comment puis-je vous aider aujourd\'hui ?',
    chatbotTitle: 'Support Mouvement Suivant',
    chatbotPlaceholder: 'Tapez votre message...',
    chatbotError: 'Désolé, j\'ai des difficultés à répondre en ce moment. Veuillez réessayer ou contacter le service clientèle.',
    error: 'Erreur',
  }
};