// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqqggvtodrgbboebvglh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcWdndnRvZHJnYmJvZWJ2Z2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDIyODYsImV4cCI6MjA2ODAxODI4Nn0.Tm1XpFIopztqPXT3NgNcVkHOjsKecjbMu9gmTW4XWJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});